### ISSUE TITLE
Can't create shape wirh sprite

### ISSUE THREAD

**Issue by Reptoh** [sbiermanlytle/iioEngine#42]
In version 1.4.0 I can't create shape with sprite/image. I research documentation, noted prepGraphics method in older version. Maybe I missed something in new version?

**Comment by sbiermanlytle** [comment]
Is this for a Box2d shape or an iio shape?

**Comment by Reptoh** [comment]
Sorry, box2d shape

**Comment by sbiermanlytle** [comment]
Yes it looks like image attachment isn't working right now in iio 1.4. This will be the next priority but still may take up to a few weeks to get the fix out.

I suggest using iio 1.2 (iioEngine) for this purpose until then. This page has a demo app with Box2d + images: http://iioengine.iioinc.com/demos

you can download the full source code for the engine and the demo here: https://github.com/iioinc/iio.js/tree/v1.2-iioengine

**Comment by sbiermanlytle** [comment]
FYI the Box2d syntax for 1.2 and 1.4 is very similar, so upgrading won't be too bad if you want to do that once the fix is released.

**Comment by Reptoh** [comment]
Thanks for answer! I already got 1.2 with examples. I tried open app on mobile devices: it works fine, but without events. 

@sbiermanlytle 
Do you plan support mobile devices?

**Comment by sbiermanlytle** [comment]
iio doesn't listen for touch events by default, but they can be added easily with the JS standard library, check out these docs for examples: http://iioengine.iioinc.com/docs/iio-basics#input

And yes, built in mobile feature are going to be the big addition in iio 2.0 - code in JS and deploy straight to iOS, Android, etc

**Comment by Reptoh** [comment]
Great! Thanks for answering!

**Comment by maverickteckh** [comment]
@Reptoh please close this issue!
